---
title: "COVID-19 deaths"
subtitle: [OpenCanada.info](http://OpenCanada.info)
output: html_document
author: "Sources: PHAC"

runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include=T)
```

## Settings: {.sidebar}

Source: 
cases and deaths data (.csv)
<https://health-infobase.canada.ca/src/data/covidLive/covid19-download.csv> (linked at <https://health-infobase.canada.ca/covid-19>)

## 1: *** Covid Cases/Deaths *** 

### Source 1:  By province- all ages

```{r}


################################################################ # 
# https://health-infobase.canada.ca/covid-19/current-situation.html -----
################################################################ # 

# Figure 1. Types of statistics Count (Rate per 100,000 population) of Types of measures total deaths  of COVID-19, Types of statistics province/territory  as of 
url <- "https://health-infobase.canada.ca/src/data/covidLive/covid19-download.csv"
dt01  <- fread(url)
dt01[c(1,.N)]
fwrite(dt01, "phac-cases.csv")

# dt01[, .(.N, totalcases,  numdeaths_last7, ratecases_last7, population=numdeaths_last7/ratecases_last7*100000), by = .(date, prname)]

dt <- dt01

dt [, ( names(dt) %wo% c("date", "prname", "numdeaths",  "ratedeaths", "update", "numdeaths_last7", "ratedeaths_last7") ):= NULL]
setnames(dt, c("date", "prname"), c("Date", "GEO"))
setorder(dt, -Date)
dt[, GEO:=fct_inorder(GEO)]
dt[GEO=="Alberta"]
dt[, pop1:= round(numdeaths_last7/ratedeaths_last7 * 100000, -3)] #
dt[, pop0:= round(numdeaths/ratedeaths * 100000, -3)] # 4.543.000  vs.  4,482,385	4,502,858	4,543,111	4,601,314


dt %>%   ggplot() +     # guides(x =  guide_axis(angle = 60))  +
  geom_line(aes(x=Date, y=ratedeaths_last7) )+
  facet_grid( GEO  ~., scales = "fix")

dt %>%   ggplot() +     # guides(x =  guide_axis(angle = 60))  +
  geom_line(aes(x=Date, y=numdeaths_last7) )+
  facet_grid( GEO  ~., scales = "free")

#  https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710000901
# Alberta  4,429,077	4,436,944	4,443,773	4,466,124	4,482,385	4,502,858	4,543,111	4,601,314

# # Figure 2. Weekly number of COVID-19  cases (n=4,297,215) in Canada as of January
# url <- "https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-weeklyEpiCurve.csv"
# dt02  <- fread(url)
# dt02[c(1,.N)]
# #          date cases deaths
# #        <IDat> <int>  <int>
# # 1: 2020-01-18     7      0
# # 2: 2023-01-21  8426     26

```


### By age - national


```{r}

# Figure 3. Weekly number of COVID-19 cases deceased by age group in Canada as of January 21, 2023
url <-  "https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-ageGender.csv"
dt  <- fread(url)
dt[c(1,.N)]
fwrite(dt, paste0("phac-cases-by-age-", dateToday, ".csv"))
dt <- dt [status      == "deaths"]

setnames(dt, c("date", "age_group", "gender"), c("Date", "Age", "Sex"))
dt[, Sex := gsub("all", "Both sexes", Sex)]
# dt[, Sex := gsub("male", "Males", Sex)]
# dt[, Sex := gsub("female", "Females", Sex)]

setorder(dt, -Date) # age == "0 to 11"


dt$Age %>% u
dt$Sex %>% u
dt[   sex=="male"][1:50]


#          date status age_group gender count rate_per_100000
#        <IDat> <char>    <char> <char> <int>           <num>
# 1: 2020-01-18  cases   0 to 11   male     1          0.0408
# 2: 2023-01-21 deaths       all    all    10          0.0257

factors <- c('Sex', 'Age')

dt[, pop:=round(count/rate_per_100000 * 100000, -3)]

  dt[, `Weekly (13W SMA)`:= as.integer(frollmean(count, 4, align = "left", fill = 0)), by = factors]


  
# dt [Sex =="Both sexes"] %>%   ggplot() +     guides(x =  guide_axis(angle = 60))  +
#   geom_line(aes(x=Date, y=rate_per_100000      , col=Sex) )+
#   facet_grid( Age ~ Sex, scales = "free")




g <- dt [Sex =="Both sexes"]  %>%   ggplot() +     
  guides(x =  guide_axis(angle = 60))  +
        theme(legend.position = "bottom")  +
  geom_line(aes(x=Date, y=`Weekly (13W SMA)`), col="red" )+
  facet_grid( . ~ Age, scales = "fixed") +
     
    labs( title = "COVID-19 Cases deceased, by age group. All sexes and all provinces combined",
          # subtitle = "All sexes and all provinces combined",
          caption = paste0 ("Source: https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-ageGender.csv",
                            "\nGenerated by OpenCanada.info Tracker on ", dateToday),

          x=NULL, col=NULL
    )


    # g.add.pandemic <- function(g) {
      alp = 0.3
      for (i in 1:length(period)) {
        g <- g + geom_vline(xintercept=period[i], linetype=5, alpha=alp,  col="darkgrey", size=1)
      }
      # g <- g + xlim(input$date[1], input$date[2])
      g <- g + geom_vline(xintercept=period[1], linetype=1, alpha=alp,  col="darkgrey", size=4)
 
    # }
    
    # g <- g + g.add.pandemic(g)
      g

```


##  2: *** Vaccination + population ***

Source: Public Health Agency of Canada - [COVID-19 vaccination in Can
ada](https://health-infobase.canada.ca/covid-19/vaccination-coverage/)

### By province - all ages - NO dose information !

```{r}

################################################################ # 
# https://health-infobase.canada.ca/covid-19/vaccination-coverage/ #####
################################################################ # 

# Figure 1
url <- "https://health-infobase.canada.ca/src/data/covidLive/vaccination-coverage-map.csv"
dtv1  <- fread(url)


# Figure 5
url <- "https://health-infobase.canada.ca/src/data/covidLive/vaccination-coverage-byVaccineType.csv"
dtv3  <- fread(url)

```

### Vaccine administration - by province, dose, age, gender


```{r}
# 2023-02-03, 2023-02-11


cVaccines <- COpenData$new()
cVaccines$url
# cVaccines$dt <- readRDS(url )

# Figure 3
phac.csv <- "vaccination-coverage-byAgeAndSex-overTimeDownload.csv"

url <- paste0("https://health-infobase.canada.ca/src/data/covidLive/",phac.csv)
dt  <- fread(url)
saveRDS(dt, paste0(phac.csv, ".Rds") ) 
dt <- readRDS( paste0(phac.csv, ".Rds") ) 
if (F) {
  url.zip = paste0(phac.csv, "-", dateToday,".zip")
  write.csv(dt, file=gzfile( url.zip  ) )
  write.csv(dt, paste0(phac.csv, "-", dateToday,".csv"))
}

dt[c(1,.N)]
dt %>% names
dt$prfname   <- dt$pruid <- NULL

dt$age %>% u
dt$sex %>% u
dt <- dt[ age %ni% c("Not reported", "Unknown", "0–15", "16–69","70–74" , "75–79", "18–69","0–17" )]



setnames(dt, "prename", "GEO")
setnames(dt, "week_end", "Date")
setcolorder(dt, "Date")

if (T) {
  dtPop = dt [, .(population = round( numtotal_atleast1dose / proptotal_atleast1dose  * 100, -2) ), by=c("Date", cVaccines$factors) ]
  
  
  if (F) {
    dtPop [prename== "Canada" & !is.na(population) & 
          # sex=="f" & 
          age=="12–17"
    ] [1:3] # population adds up !
    
    dtPop [prename== "Canada" & !is.na(population)   ] [1:11] # population adds up ? does not have 80+
    dtPop [prename== "Alberta" & !is.na(population)   ] [1:11] # population adds up ? does not have 80+
    dtPop [prename== "Ontario" & !is.na(population)   ] [1:11] # population adds up ! 80+
    
    dtPop$sex %>% u
    dtPop$age %>% u
    
    dt [prename== "Canada"]
  }
  
  
  
}

dt <- dt[sex=="All sexes"]; dt$sex <- NULL

cols <-  dt %>% names %wo% c("prename"  , "week_end"  ,  "sex"   , "age" );cols
cols.weekly <- paste0(cols, ".weekly")

dt [, (cols):= lapply(.SD, as.numeric), .SDcols = cols]
setorder(dt, week_end     ) # to do shift
dt [, (cols.weekly):= lapply(.SD, function(x) {x-shift(x,1) }), .SDcols = cols, by=.(prename, age ) ]
setorder(dt, - week_end )# setorder(dt, - week_end ) # for viewing 


cols.metrics.num <- c(   "numtotal_atleast1dose" ,  "numtotal_partially"   , "numtotal_fully"   ,   "numtotal_additional" , "numtotal_2nd_additional" , "numtotal_recent_fullyoradditional"   )
cols.metrics<- c(   "total_atleast1dose" ,  "total_partially"   , "total_fully"   ,   "total_additional" , "total_2nd_additional" , "total_recent_fullyoradditional"   )
cols.metrics.prop <-  paste0("prop",cols.metrics)
cols.metrics.num.weekly <- paste0(cols.metrics.num, ".weekly")
cols.metrics.prop.weekly <- paste0(cols.metrics.prop, ".weekly")

str_replace(cols.metrics.num, "numtotal_", "")

for (i in 1:length(cols.metrics)) {
  col.prop.weekly=cols.metrics.prop.weekly[i]
  col.weekly=cols.metrics.prop.weekly[i]
  
}
# dt[, (cols.metrics.prop.weekly):= lapply(.SD, function(x) {x/population} ), cols.metrics.num.weekly]

if (F) {
  metric <- "Unnamed: 22" # WHAT ARE THESE??? These are POPULATION for all 7 days of reporting week
  metric.num <- metric 
  dt[prename== "Canada" & !is.na(`Unnamed: 22`)]$`Unnamed: 22`
  
  dt[!is.na(`Unnamed: 22`)]  %>%   ggplot(aes(x=week_end)) +     
    guides(x =  guide_axis(angle = 60))  +
      scale_x_date(date_labels = "%b %Y", date_breaks = "3 months") +
    facet_grid( prename ~ age, scale="free_y" ) + # ylim(0, NA) +
    geom_point(aes(y=`Unnamed: 22`, size=3), ) + labs(y=metric, x=NULL)
  
  dt[, .SD[1], by= prename ] %>% datatable.title()
  
}

period = c(
  # ymd("2010-01-05"), # early prepandemic, early flu waves 
  # ymd("2020-01-01"), # four new cause categories added: 3 for covid + NO_INFO
  ymd("2021-11-01"), # 
  # ymd("2022-01-01"), 
  ymd("2022-03-01") # # 
)


# PLOTTIN ------


######################################### #

i=1
for (i in 1:length(cols.metrics)) { 
  
  metric <- cols.metrics[i];metric
  # metric.num <- cols.metrics.num [i]
  # metric.prop <- cols.metrics.prop [i]
  metric.weekly <- cols.metrics.num.weekly [i] 
  metric.title <- str_replace(metric, "total_", "")
  
  
  g <- dt  %>%   ggplot(aes(x=week_end)) +     
    guides(x =  guide_axis(angle = 60))  +
    facet_grid( prename ~ age, scale="free_y" ) +  ylim(0, NA) +
    
    
    labs(y="Doses administered weekly", 
         x=NULL,          title = metric.title,
         caption=paste("Generated by OpenCanada.info tracker on", dateToday)
    )
  
  if (T) { # input$vline) {
    alp = 0.5
    for (iii in 1:length(period)) {
      g <- g + geom_vline(xintercept=period[iii], linetype=5, aplha=alp,  col="grey")
    }
    # g <- g + xlim(input$date[1], input$date[2])
  }
  
  
  g <- g + geom_line(aes(y=get(metric.weekly)) ) # , col=i, linetype=i) 
  
  ggsave(paste("png/", i, "-", metric.title, "-2.png"), width=12, height=9)
  
  print(i)
  print(metric); 
  
}

print(g)



```


## 3: Vaccince safety ----

```{r eval=FALSE, include=FALSE}



################################################################ # 
# https://health-infobase.canada.ca/covid-19/vaccine-safety/
############################################################### ## 


url <- "https://github.com/opencanada-info/phac-covid-vaccine-safety/raw/main/side-effects-2023-01-20.csv"
dt <- fread(url, skip=5)
saveRDS(dt, 'phac-safety-till-2023-01-06) # accessed 11 feb 2023




```

